export const aiScenarios = [
  "success",
  "delayedSuccess",
  "delayedFailure",
  "delayedModels",
  "invalidOnce",
  "invalidDraft",
  "usageLimit",
  "incompleteDraft",
  "aiFailed",
  "noSmallModel",
  "removedModel",
  "emptyModels",
  "modelsFailed",
  "handoffFailed",
] as const;
