import { contextBridge, ipcRenderer } from "electron";
import type { AppearanceBootstrap } from "../domain/appearance";
const methods = [
  "load",
  "getAppInfo",
  "setDevelopmentMode",
  "developmentScenario",
  "copyList",
  "copyWeek",
  "importReceipt",
  "save",
  "setLanguage",
  "setAppearance",
  "setAIModel",
  "cancelTransfer",
  "buildBasket",
  "compareStores",
  "getContextOptions",
  "changeContext",
  "recordError",
  "openRelease",
  "openNotices",
  "accept",
  "setPackSize",
  "omit",
  "prepare",
  "transferDisplayed",
  "execute",
  "recover",
  "scenario",
  "exportList",
  "exportData",
  "exportDiagnostics",
  "importData",
  "searchStores",
  "loginStore",
  "checkStoreLogin",
  "cancelStoreLogin",
  "logoutStore",
  "openStoreCart",
  "storeView",
  "hideStore",
  "storeAction",
  "signInAI",
  "cancelAI",
  "signOutAI",
  "modelsAI",
  "usageAI",
  "generate",
  "importRecipe",
  "approveDraft",
  "confirmPurchase",
  "newWeek",
  "reuseWeek",
] as const;
contextBridge.exposeInMainWorld("korikone", {
  ...Object.fromEntries(
    methods.map((method) => [
      method,
      (input: unknown) => ipcRenderer.invoke(`app:${method}`, input),
    ]),
  ),
  getAppearanceBootstrap: () => ipcRenderer.sendSync("app:appearanceBootstrap"),
  onAppearanceChange: (callback: (value: AppearanceBootstrap) => void) => {
    const listener = (
      _event: Electron.IpcRendererEvent,
      value: AppearanceBootstrap,
    ) => callback(value);
    ipcRenderer.on("app:appearanceChanged", listener);
    return () => ipcRenderer.removeListener("app:appearanceChanged", listener);
  },
});
